/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_invo_ServiceCtrl */


#ifndef _Included_com_example_invo_ServiceCtrl
#define _Included_com_example_invo_ServiceCtrl
#ifdef __cplusplus
extern "C" {
#endif

#define LOG_TAG "inv"

#define LOGD(...) 	\
	{				\
	__android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__);	\
	}

#define LOGE(...) 	\
	{				\
	__android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__);	\
	}

#ifndef BYTE
#define BYTE unsigned char
#endif

extern jclass g_objclass;
extern jobject g_obj;
extern JavaVM *g_JavaVM;
extern jmethodID g_mid_LoadX509Cert;
extern jmethodID g_mid_X509PrivateEncrypt;
extern jmethodID g_mid_X509PrivateDecrypt;

/*
 * Class:     com_example_invo_ServiceCtrl
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_invo_ServiceCtrl_start
  (JNIEnv *, jobject);

/*
 * Class:     com_example_invo_ServiceCtrl
 * Method:    initJavaObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_invo_ServiceCtrl_initJavaObject
  (JNIEnv *, jobject);

/*
 * Class:     com_example_invo_ServiceCtrl
 * Method:    startFakeVPN
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_example_invo_ServiceCtrl_startFakeVPN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
